# Generated by Django 4.0.3 on 2022-03-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(choices=[('oslo', 'Oslo'), ('trondheim', 'Trondheim'), ('stavanger', 'Stavanger'), ('bergen', 'Bergen')], max_length=9)),
                ('date', models.DateField(auto_now=True)),
                ('listingType', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=1)),
                ('eventType', models.CharField(choices=[('t', 'Theatre'), ('c', 'Concert'), ('p', 'Party')], max_length=2)),
                ('complete', models.BooleanField(default=False)),
                ('price', models.PositiveBigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
