# Generated by Django 4.0.2 on 2022-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='event_type',
            field=models.CharField(choices=[('t', 'Theatre'), ('c', 'Concert'), ('f', 'Festival')], max_length=2),
        ),
    ]
