# Generated by Django 4.0.3 on 2022-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='listing_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='event_type',
            field=models.CharField(choices=[('konsert', 'Konsert'), ('teater', 'Teater'), ('festival', 'Festival')], default='konsert', max_length=10),
            preserve_default=False,
        ),
    ]
