# Generated by Django 4.0.3 on 2022-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_first_name_profile_last_name'),
        ('listings', '0004_rename_type_listing_listing_type_listing_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested', to='users.profile'),
        ),
    ]
